/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.10.0
 *
 * Project: 'TFLiteRT_HelloWorld.Debug+STM32F756ZGTx' 
 * Target:  'Debug+STM32F756ZGTx' 
 */

#ifndef PRE_INCLUDE_GLOBAL_H
#define PRE_INCLUDE_GLOBAL_H

/* tensorflow::Machine Learning:TensorFlow:Kernel&CMSIS-NN@1.25.2 */
// enabling global pre includes 
        #define TF_LITE_STATIC_MEMORY 1
        #define CMSIS_NN


#endif /* PRE_INCLUDE_GLOBAL_H */
