
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "D:/SPB_DATA/.vcpkg/artifacts/2139c4c6/tools.kitware.cmake/3.31.5/share/cmake-3.31/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:18 (project)"
    message: |
      The system is: Windows - 10.0.26100 - AMD64
...
