/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.10.0
 *
 * Project: 'BSD_Client.Debug+STM32F756ZGTx' 
 * Target:  'Debug+STM32F756ZGTx' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H

/* ARM::CMSIS:RTOS2:Keil RTX5&Source@5.9.0 */
#define RTE_CMSIS_RTOS2                 /* CMSIS-RTOS2 */
#define RTE_CMSIS_RTOS2_RTX5            /* CMSIS-RTOS2 Keil RTX5 */
#define RTE_CMSIS_RTOS2_RTX5_SOURCE     /* CMSIS-RTOS2 Keil RTX5 Source */
/* Keil::Network&MDK:CORE@8.0.0 */
#define RTE_Network_Core                /* Network Core */
/* Keil::Network&MDK:Interface:ETH@8.0.0 */
#define RTE_Network_Interface_ETH_0     /* Network Interface ETH 0 */

/* Keil::Network&MDK:Socket:BSD@8.0.0 */
#define RTE_Network_Socket_BSD          /* Network Socket BSD */
/* Keil::Network&MDK:Socket:TCP@8.0.0 */
#define RTE_Network_Socket_TCP          /* Network Socket TCP */
/* Keil::Network&MDK:Socket:UDP@8.0.0 */
#define RTE_Network_Socket_UDP          /* Network Socket UDP */


#endif /* RTE_COMPONENTS_H */
